version: '3'

services:
    reverseproxy:
        build: ./docker_reverseproxy
        container_name: reverseproxy
        restart: always
        ports:
            - "${EXTERNAL_PORT:-80}:80"

    lanchonete:
        build: ./docker_lanchonete
        container_name: lanchonete
        restart: always
        ports:
            - "8081:8081"
        depends_on:
            - reverseproxy
